version: '3'

services:
  db-backup:
    image: mariadb
    container_name: db-backup
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db-backup:/var/lib/mysql
    env_file:
      - db.env
      - .env
    networks:
      - default-backup

  adminer-backup:
    image: adminer:4.6.3
    container_name: adminer-backup
    environment:
      - VIRTUAL_HOST=${ADMINER_MARIA_VIRTUAL_HOST}-backup
      - LETSENCRYPT_HOST=${ADMINER_MARIA_LETSENCRYPT_HOST}-backup
      - LETSENCRYPT_EMAIL=it@oberfeld.be
    networks:
      - proxy-tier-backup
      - default-backup

  nextcloud-backup:  
    container_name: nextcloud_backup
    build: ./nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-backup:/var/www/html
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_VIRTUAL_HOST}-backup
      - VIRTUAL_HOST=${NEXTCLOUD_VIRTUAL_HOST}-backup
      - LETSENCRYPT_HOST=${NEXTCLOUD_LETSENCRYPT_HOST}-backup
      - LETSENCRYPT_EMAIL=it@oberfeld.be
      - MYSQL_HOST=db-backup
    env_file:
      - db.env
      - .env
    depends_on:
      - db-backup
    networks:
      - proxy-tier-backup
      - default-backup

  portainer-backup:
    image: portainer/portainer
    container_name: portainer-backup
    command: --admin-password ${PORTAINER_PASSWORD_HASH}
    restart: always
    volumes:
      - portainer_data-backup:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=${PORTAINER_VIRTUAL_HOST} 
      - LETSENCRYPT_HOST=${PORTAINER_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=it@oberfeld.be
    env_file:
      - .env
    networks:
      - proxy-tier-backup
  
  proxy-backup:
    build: ./proxy
    restart: always
    container_name: proxy-backup
    ports:
      - 8080:80
      - 4443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: ${USE_LETSENCRYPT}
    volumes:
      - certs-backup:/etc/nginx/certs:ro
      - vhost.d-backup:/etc/nginx/vhost.d
      - html-backup:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier-backup

  letsencrypt-companion-backup:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs-backup:/etc/nginx/certs
      - vhost.d-backup:/etc/nginx/vhost.d
      - html-backup:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier-backup
    depends_on:
      - proxy-backup

  volumerize-backup:
    container_name: volumerize-backup
    build: ./volumerize
    environment:
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=${BACKUP_TARGET}
      - VOLUMERIZE_JOBBER_TIME=0 0 3 * * *
      - VOLUMERIZE_CONTAINERS=db-backup nextcloud-backup
      - PASSPHRASE=${BACKUP_PASSWORD}
      - VOLUMERIZE_FULL_IF_OLDER_THAN=1M
      - TZ=Europe/Berlin
      - AWS_ACCESS_KEY_ID=    ${BACKUP_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BACKUP_AWS_SECRET_ACCESS_KEY}
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--file-prefix-archive=archive-
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - db-backup:/source/db  
      - nextcloud-backup:/source/nextcloud
#      - ./keys:/keys

volumes:
  db-backup:
  nextcloud-backup:
  certs-backup:
  vhost.d-backup:
  html-backup:
  portainer_data-backup:

networks:
  proxy-tier-backup:
  default-backup:
   
