version: '3.2'

services:  
  volumeris3:
    image: blacklabelops/volumerize:1.7.1
    environment:
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=${BACKUP_TARGET_S3}
      - VOLUMERIZE_JOBBER_TIME=0 0 3 * * *
      - VOLUMERIZE_CONTAINERS=${COMPOSE_PROJECT_NAME}_db_1 ${COMPOSE_PROJECT_NAME}_nextcloud_1
      - PASSPHRASE=${BACKUP_PASSWORD}
      - VOLUMERIZE_FULL_IF_OLDER_THAN=1M
      - TZ=Europe/Berlin
      - AWS_ACCESS_KEY_ID=    ${BACKUP_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${BACKUP_AWS_SECRET_ACCESS_KEY}
      - VOLUMERIZE_DUPLICITY_OPTIONS=--file-prefix-archive=archive- --s3-use-new-style --volsize 2000 --s3-multipart-chunk-size 50
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: db
        target: /source/db
        read_only: ${NO_RESTORE:-true}
      - type: volume
        source: nextcloud
        target: /source/nextcloud
        read_only: ${NO_RESTORE:-true}